In [2]:
import yfinance as yf
import pandas as pd

def call(s):
    min = s.min()
    max = s.max()
    return pd.Series([max, min],index=['最高價','最低價'])

#國泰金(2882.TW),新光金(2888.TW),中信金(2891.TW),台新金(2887.TW)
all_data = {ticker:yf.download(ticker) for ticker in ['2882.TW','2888.TW','2891.TW','2887.TW']}

all_data1 = {ticker:df['Adj Close'] for ticker,df in all_data.items()}
prices_df = pd.DataFrame(all_data1)

prices_df.columns = ['國泰金','新光金','中信金','台新金']
prices_df1 = prices_df.dropna()
prices_df1_2023 = prices_df1.loc['2023']
prices_df1_2023

# 取得最高價, 最低價 dataFrame
df_high_low_value = prices_df1_2023.apply(call)


# 取得最低價日期 series, 再轉成[最低價日期] dataFrame
series_low_date = prices_df1_2023.idxmin()
df_low_date = pd.DataFrame([series_low_date], index=['最低價日期']).astype(str)

# 取得最高價日期 series, 再轉成[最高價日期] dataFrame
series_high_date = prices_df1_2023.idxmax()
df_high_date = pd.DataFrame([series_high_date], index=['最高價日期']).astype(str)

#合併最後結果
df_total = pd.concat([df_high_low_value, df_low_date, df_high_date], ignore_index=False)
df_total

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

              國泰金         新光金         中信金         台新金
最高價     45.648304        9.83   27.176025   17.105072
最低價     37.808987        7.99   19.154709   13.100577
最低價日期  2023-01-03  2023-03-20  2023-03-17  2023-01-03
最高價日期  2023-08-01  2023-08-01  2023-12-14  2023-07-26

In [3]:
import yfinance as yf
import pandas as pd

def call(s):
    min = s.min()
    max = s.max()
    return pd.Series([max, min],index=['最高價','最低價'])

#國泰金(2882.TW),新光金(2888.TW),中信金(2891.TW),台新金(2887.TW)
all_data = {ticker:yf.download(ticker) for ticker in ['2882.TW','2888.TW','2891.TW','2887.TW']}

all_data1 = {ticker:df['Adj Close'] for ticker,df in all_data.items()}
prices_df = pd.DataFrame(all_data1)

prices_df.columns = ['國泰金','新光金','中信金','台新金']
prices_df1 = prices_df.dropna()
prices_df1_2023 = prices_df1.loc['2023']
prices_df1_2023

# 取得最高價, 最低價 dataFrame
df_high_low_value = prices_df1_2023.apply(call)


# 取得最低價日期 series, 再轉成[最低價日期] dataFrame
series_low_date = prices_df1_2023.idxmin()
df_low_date = pd.DataFrame([series_low_date], index=['最低價日期']).astype(str)

# 取得最高價日期 series, 再轉成[最高價日期] dataFrame
series_high_date = prices_df1_2023.idxmax()
df_high_date = pd.DataFrame([series_high_date], index=['最高價日期']).astype(str)

#合併最後結果
df_total = pd.concat([df_high_low_value, df_low_date, df_high_date], ignore_index=False)
df_total

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

              國泰金         新光金         中信金         台新金
最高價     45.648304        9.83   27.176025   17.105072
最低價      37.80899        7.99   19.154709   13.100577
最低價日期  2023-01-03  2023-03-20  2023-03-17  2023-01-03
最高價日期  2023-08-01  2023-08-01  2023-12-14  2023-07-26

In [4]:
results = {}
for ticker in prices_df1_2023.columns:
    max_price = prices_df1_2023[ticker].max()
    min_price = prices_df1_2023[ticker].min()
    max_date = prices_df1_2023[ticker].idxmax()
    min_date = prices_df1_2023[ticker].idxmin()
    results[ticker] = {
        '最高收盤價': max_price,
        '最低收盤價': min_price,
        '最高收盤價日期': max_date,
        '最低收盤價日期': min_date
    }

results_df = pd.DataFrame(results).T
print(results_df)

         最高收盤價      最低收盤價              最高收盤價日期              最低收盤價日期
國泰金  45.648304   37.80899  2023-08-01 00:00:00  2023-01-03 00:00:00
新光金       9.83       7.99  2023-08-01 00:00:00  2023-03-20 00:00:00
中信金  27.176025  19.154709  2023-12-14 00:00:00  2023-03-17 00:00:00
台新金  17.105072  13.100577  2023-07-26 00:00:00  2023-01-03 00:00:00